[global]
daemonize = no

[www]
user = www-data
group = www-data
listen = 9000
pm = static
pm.max_children = 20
pm.max_requests = 10000
listen.backlog = 1024
request_terminate_timeout = 30s
request_slowlog_timeout = 5s
slowlog = /proc/self/fd/2
security.limit_extensions = .php
clear_env = no
catch_workers_output = yes
