version: "3"

server:
  command: "php worker-roadrunner.php"
  relay: pipes

http:
  address: 0.0.0.0:8080
  middleware: [static, gzip, headers]
  pool:
    num_workers: 0
    supervisor:
      max_worker_memory: 192
  static:
    dir: ./public
    forbid: [.php, .htaccess]
  headers:
    response:
      Cache-Control: no-cache

logs:
  mode: production
  level: warn
